---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Dodgeball
description: În acest proiect vei învăța cum să creezi o platformă pentru un joc în care va trebui să te ferești de mingile care se mișcă și să ajungi la sfârșitul nivelului.
original_url: https://codeclubprojects.org/en-GB/scratch/dodgeball
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Dodgeball