---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Između dvije vatre
description: Kreiraj platformsku igru u kojoj treba da izbjegavaš lopte koje se kreću i dođeš do kraja nivoa.
original_url: https://codeclubprojects.org/en-GB/scratch/dodgeball
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps:
  - title: Uvod
  - title: Kretanje karaktera
  - title: 'Izazov: Dovršavanje nivoa'
  - title: Gravitacija i skokovi
  - title: 'Izazov: Poboljšan skok'
  - title: Izbjegavanje lopti
  - title: 'Izazov: Slučajne lopte'
  - title: Laseri!
  - title: 'Izazov: Više prepreka'
  - title: 'Izazov: Poboljšana gravitacija'
  - title: 'Izazov: Više života'
