---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Dodgeball
description: Crea un gioco a piattaforme in cui dovrai schivare le palle in movimento e raggiungere la fine del livello.
original_url: https://codeclubprojects.org/en-GB/scratch/dodgeball
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduzione
- title: Movimento del personaggio
- title: 'Sfida: Completare il livello'
- title: Gravità e salti
- title: 'Sfida: Salto migliorato'
- title: Palle da schivare
- title: 'Sfida: Palle a caso'
- title: Laser!
- title: 'Sfida: Altri ostacoli'
- title: 'Sfida: Salto migliorato'
- title: 'Sfida: Altre vite'